MyFirstApp/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyFirstApp.Model;

namespace MyFirstApp.Controllers
{
    [Route("/api/Book")]
    [ApiController]
    public class BookController : Controller

    {
        private readonly ApplicationDbContext _db;
        public BookController(ApplicationDbContext db)
        {
            _db = db;
        }
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            return Json(new { data = await _db.Book.ToListAsync() });
        }
        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var bookFromDb = await _db.Book.FirstOrDefaultAsync(u => u.Id == id);

            if (bookFromDb == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            _db.Book.Remove(bookFromDb);
            await _db.SaveChangesAsync();
            return Json(new { success = true, message = "Delete Successful" });


        }
    }
}

MyFirstApp/Pages/BookList/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyFirstApp.Pages.BookList
{
    public class AboutModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

MyFirstApp/Pages/BookList/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MyFirstApp.Model;

namespace MyFirstApp.Pages.BookList
{
    public class CreateModel : PageModel
    {
        private readonly ApplicationDbContext _db;
        public CreateModel(ApplicationDbContext db)
        {
            _db = db;
        }
        [BindProperty]
        public Book Books { get; set; }
        public void OnGet()
        {

        }
        public  async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                await _db.Book.AddAsync(Books);
                await _db.SaveChangesAsync();
                return RedirectToPage("Index");

            }
            else
            {
                return Page();
            }
        }
    }
}

MyFirstApp/Pages/BookList/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MyFirstApp.Model;

namespace MyFirstApp.Pages.BookList
{
    public class EditModel : PageModel
    {
        private  ApplicationDbContext _db;
        public EditModel(ApplicationDbContext db)
        {
            _db = db;
        }
        [BindProperty]
        public Book Books { get; set; }
        public async Task OnGet(int id)
        {
            Books = await _db.Book.FindAsync(id);

        }
        public async Task<IActionResult> OnPost() {
            if (ModelState.IsValid)
            {
                var BookFormDb = await _db.Book.FindAsync(Books.Id);
                BookFormDb.Name = Books.Name;
                BookFormDb.Author = Books.Author;
                BookFormDb.ISBN = Books.ISBN;

                await _db.SaveChangesAsync();
                return RedirectToPage("Index");


            }
            return RedirectToPage();
        }
        
}
}

MyFirstApp/Pages/BookList/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MyFirstApp.Model;

namespace MyFirstApp.Pages.BookList
{
    public class IndexModel : PageModel
    {
        private readonly ApplicationDbContext _db;
        public IndexModel(ApplicationDbContext db)
        {
            _db = db;
        }
        public IEnumerable<Book> Books { get; set; }
        public async Task OnGet()
        {
            Books = await _db.Book.ToListAsync();
        }
        public async Task<IActionResult> OnPostDelete(int id)
        {
            var Book = await _db.Book.FindAsync(id);
            if (Book == null)
            {
                return NotFound();
            }
            _db.Book.Remove(Book);
            await _db.SaveChangesAsync();
            return RedirectToPage("Index");

        }
    }
}

MyFirstApp/Pages/BookList/Index1.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyFirstApp.Pages.BookList
{
    public class Index1Model : PageModel
    {
        public void OnGet()
        {
        }
    }
}

MyFirstApp/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace MyFirstApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

MyFirstApp/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace MyFirstApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()//this is  handler 
        {

        }
        //public void OnPost()//
        //{

        //}
    }
}

MyFirstApp/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace MyFirstApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

MyFirstApp/Pages/BookList/About.cshtml
@page
@model MyFirstApp.Pages.BookList.AboutModel
@{
    ViewData["Title"] = "About";
}
<div class="text-center">
<h1 style= "color:gey" >About  page</h1>
<p style= "font-size:20px"> This is good application for any user there we can create book details easily , update and delete also we can 
do easily.</p>
</div>

MyFirstApp/Pages/BookList/Create.cshtml
@page
@model MyFirstApp.Pages.BookList.CreateModel
<br/>

<h2 class = "text-info">Create New  Book </h2>
<br/>
<div class = "border container" style="padding:30px">
<form method="post">
<div class ="text-Danger" asp-validation-summary="ModelOnly"></div>
   <div class= "form-group row">
        <div class ="col-3">
         <label asp-for="Books.Name"></label>
       </div>
    <div class ="col-6">
       <input asp-for="Books.Name" class="form-control"/>
      </div>      
<span asp-validation-for="Books.Name" class="text-danger"></span>
   </div>
                <div class= "form-group row">
        <div class ="col-3">
         <label asp-for="Books.Author"></label>
       </div>
    <div class ="col-6">
       <input asp-for="Books.Author" class="form-control"/>
      </div>
      <span asp-validation-for="Books.Author" class="text-Danger"></span>
   </div>
           <div class= "form-group row">
        <div class ="col-3">
         <label asp-for="Books.ISBN"></label>
       </div>
    <div class ="col-6">
       <input asp-for="Books.ISBN" class="form-control"/>
      </div>
      <span asp-validation-for="Books.ISBN" class="text-Danger"></span>

   </div>
     <div class= "form-group row">
        <div class ="col-3 offset-3">
         <input type ="submit" value="Create"  class="btn btn-primary form-control"/>
       </div>
    <div class ="col-3">
       <a asp-page="Index" class=" btn btn-success form-control">Back to List</a>
      </div>
   </div>
</form>
</div>
@section Scripts{
 <partial name ="_ValidationScriptsPartial"/>
 }


 

MyFirstApp/Pages/BookList/Edit.cshtml
@page
@model MyFirstApp.Pages.BookList.EditModel
<br/>

<h2 class = "text-info">Edit  Book </h2>
<br/>
<div class = "border container" style="padding:30px">
<form method="post">
<input  type="hidden" asp-for="Books.Id"/>
<div class ="text-Danger" asp-validation-summary="ModelOnly"></div>
   <div class= "form-group row">
        <div class ="col-3">
         <label asp-for="Books.Name"></label>
       </div>
    <div class ="col-6">
       <input asp-for="Books.Name" class="form-control"/>
      </div>      
<span asp-validation-for="Books.Name" class="text-danger"></span>
   </div>
                <div class= "form-group row">
        <div class ="col-3">
         <label asp-for="Books.Author"></label>
       </div>
    <div class ="col-6">
       <input asp-for="Books.Author" class="form-control"/>
      </div>
      <span asp-validation-for="Books.Author" class="text-Danger"></span>
   </div>
           <div class= "form-group row">
        <div class ="col-3">
         <label asp-for="Books.ISBN"></label>
       </div>
    <div class ="col-6">
       <input asp-for="Books.ISBN" class="form-control"/>
      </div>
      <span asp-validation-for="Books.ISBN" class="text-Danger"></span>

   </div>
     <div class= "form-group row">
        <div class ="col-3 offset-3">
         <input type ="submit" value="Update"  class="btn btn-primary form-control"/>
       </div>
    <div class ="col-3">
       <a asp-page="Index" class=" btn btn-success form-control">Back to List</a>
      </div>
   </div>
</form>
</d




iv>
@section Scripts{
 <partial name ="_ValidationScriptsPartial"/>
 }


 

MyFirstApp/Pages/BookList/Index.cshtml
@page
@model MyFirstApp.Pages.BookList.IndexModel
<br />
<div class = "Container row p-0 m-0">
<div class ="col-9">
<h2 class = "text-info">Book List</h2>
</div>
<div class ="col -3">
<a  asp-page ="Create" class ="btn-info form-control" style="text-decoration: none ">Create New BooK</a>
</div>
<div class="col-12 border p-3 mt-3">

   <form method="post">`
      @if(Model.Books.Count() > 0)
      {

          <table class ="table table-striped border">
          <tr class = "table-secondary">
             <th >
                <label asp-for="Books.FirstOrDefault().Name"></label>
             </th>
             <th >
                 <label asp-for="Books.FirstOrDefault().Author"></label>
            </th>
             <th >
                 <label asp-for="Books.FirstOrDefault().ISBN"></label>
            </th>
            <th> 
         
            </th>
         </tr>
         

             @foreach(var item in Model.Books)
         {
         <tr>
            <td>
               @Html.DisplayFor(m =>item.Name)
           </td>
           <td>
              @Html.DisplayFor(m =>item.Author)
          </td>
           <td>
              @Html.DisplayFor(m =>item.ISBN)
          </td>
          <td>
          <button  asp-page-handler="Delete" asp-route-id="@item.Id"  class ="btn btn-danger btn-sm" onclick= "return confirm("Are you sure you want to delete?")">Delete</button>
          <a  asp-page="Edit" asp-route-id="@item.Id" class = "btn btn-success btn-sm text-white " style="width:52px">Edit</a>
          </td>
         </tr>
         }
       </table>

       }
   else {
    <p>No books available</p>
    }
  </form>
  </div>


  <div class="col-12" style="text-align:center">
  <br />
  <span class= "h3 text-info">OR</span>
  <br /><br />
  </div>
  <div class="col-12 border p-3 ">
  <table  id="DT_load" class ="table table-striped table-bordered" style= "width="100%">
        <thead>
            <tr>
                <th> Name</th>
                <th> Author</th>
                <th> ISBN</th>
                <th></th>
            </tr>
        </thead>
    </table>
    </div>
</div>
@section Scripts{
 <script src="~/js/bookList.js"></script>
 }

MyFirstApp/Pages/BookList/Index1.cshtml
@page
@model MyFirstApp.Pages.BookList.Index1Model
@{
}

MyFirstApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Book App</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
   
</div>

MyFirstApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyFirstApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css"/>
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css"/>


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Book App</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/BookList/Index">Book</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/BookList/About">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - BookList - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
     <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
      <script type="text/javascript" src="https://unpkg.com/sweetalert@2.1.2/dist/sweetalert.min.js"></script>
     <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
     
   
        
    @RenderSection("Scripts", required: false)
</body>
</html>